/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'steingrimur13' at '10/20/16 12:08 PM' with Gradle 3.1
 *
 * @author steingrimur13, @date 10/20/16 12:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
